pub mod annotate;
pub mod app;
pub mod capture;
#[cfg(target_os = "linux")]
pub mod daemon;
pub mod export;
pub mod history;
pub mod i18n;
pub mod ipc;
pub mod ocr;
pub mod render;
pub mod settings;
#[cfg(target_os = "linux")]
pub mod tray;
pub mod wallpaper;
pub mod winlist;
#[cfg(target_os = "linux")]
pub mod wl_windows;
